http:
  host: "localhost"
  port: "8081"
  snowflake_port: "8091"
  
https:
  private_port: "443" 
  sf_private_port: "443" 
  
jms:
  destination: "CareBenefitVerifcationRequest_Creation"
  replyTo: "CareBenefitVerifcationRequest_Creation_Success"